/* Read-only source inventory. Does not call APIs or inspect credentials. */
const fs=require('fs'),path=require('path'),vm=require('vm');
const ts=require(process.env.AUDIT_TYPESCRIPT_PATH ? path.resolve(process.env.AUDIT_TYPESCRIPT_PATH) : 'typescript');
const root=process.cwd();
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}
const files=walk('src').filter(f=>/\.(tsx?|jsx?)$/.test(f)&&!/(\.test\.|__tests__|\/test\/)/.test(f));
const source=new Map(files.map(f=>[f,fs.readFileSync(f,'utf8')]));
const ast=new Map(files.map(f=>[f,ts.createSourceFile(f,source.get(f),ts.ScriptTarget.Latest,true)]));
function visit(n,fn){fn(n);ts.forEachChild(n,c=>visit(c,fn));}
function resolve(from,s){if(!s.startsWith('.')&&!s.startsWith('@/'))return null;const base=s.startsWith('@/')?'src/'+s.slice(2):path.normalize(path.join(path.dirname(from),s));return [base,...['.ts','.tsx','.js','.jsx','/index.ts','/index.tsx'].map(x=>base+x)].find(f=>source.has(f))||null;}
const records={};
const clients=['src/api/client.ts','src/api/seo.ts'];
for(const [f,a] of ast){const r=records[f]={imports:[],apiCalls:[],directRequests:[],links:[],flags:[],lines:source.get(f).split('\n').length};const namespaces={},named={};
 for(const stmt of a.statements){if(ts.isImportDeclaration(stmt)&&ts.isStringLiteral(stmt.moduleSpecifier)){const target=resolve(f,stmt.moduleSpecifier.text);if(target)r.imports.push(target);const b=stmt.importClause?.namedBindings;if(target&&clients.includes(target)&&b){if(ts.isNamespaceImport(b))namespaces[b.name.text]=target;else for(const x of b.elements)named[x.name.text]={client:target,name:x.propertyName?.text||x.name.text};}}}
 visit(a,n=>{if(ts.isCallExpression(n)){const e=n.expression;if(ts.isIdentifier(e)&&named[e.text])r.apiCalls.push({...named[e.text],line:a.getLineAndCharacterOfPosition(n.getStart()).line+1});if(ts.isPropertyAccessExpression(e)&&ts.isIdentifier(e.expression)&&namespaces[e.expression.text])r.apiCalls.push({client:namespaces[e.expression.text],name:e.name.text,line:a.getLineAndCharacterOfPosition(n.getStart()).line+1});if((ts.isIdentifier(e)&&['fetch','authFetch','apiCall','apiCallResult','seoFetch'].includes(e.text))&&n.arguments.length){const arg=n.arguments[0];r.directRequests.push({expression:arg.getText(a),line:a.getLineAndCharacterOfPosition(n.getStart()).line+1,method:(n.getText(a).match(/method\s*:\s*['"]([A-Z]+)['"]/)||[])[1]||'GET'});}}if(ts.isStringLiteral(n)&&n.text.startsWith('/'))r.links.push(n.text);if(ts.isPropertyAccessExpression(n)&&n.expression.getText(a)==='featureFlags')r.flags.push(n.name.text);});
}
const methods={};
// Resolve nested endpoint bases and object API exports without evaluating app code.
const bases={API_BASE:'',SEO_API:''};
for(const f of clients){const a=ast.get(f);for(const st of a.statements){if(ts.isVariableStatement(st))for(const d of st.declarationList.declarations){if(d.initializer&&(ts.isTemplateExpression(d.initializer)||ts.isNoSubstitutionTemplateLiteral(d.initializer))){let v=d.initializer.getText(a).slice(1,-1);v=v.replace(/\$\{([A-Z_]+)\}/g,(all,k)=>Object.hasOwn(bases,k)?bases[k]:all);if(!v.includes('${'))bases[d.name.getText(a)]=v;}}}}
for(const f of clients){const a=ast.get(f);for(const st of a.statements){const defs=ts.isFunctionDeclaration(st)&&st.name?[[st.name.text,st]]:ts.isVariableStatement(st)?st.declarationList.declarations.filter(x=>x.initializer&&(ts.isArrowFunction(x.initializer)||ts.isFunctionExpression(x.initializer))).map(x=>[x.name.getText(a),x.initializer]):[];for(const [name,node] of defs){const text=node.getText(a),endpoints=[];visit(node,n=>{if(ts.isStringLiteral(n)||ts.isNoSubstitutionTemplateLiteral(n)||ts.isTemplateExpression(n)){let value=ts.isStringLiteral(n)?n.text:n.getText(a).slice(1,-1);value=value.replace(/\$\{(?:API_BASE|SEO_API)\}/g,'').replace(/\$\{[^}]+\}/g,'{dynamic}');if(value.startsWith('/')&&!value.includes(' '))endpoints.push(value.split('?')[0]);}});methods[f+'#'+name]={client:f,name,endpoints:[...new Set(endpoints)],line:a.getLineAndCharacterOfPosition(node.getStart()).line+1};}}}
const navFile='src/config/navigation.ts';const navCode=ts.transpileModule(source.get(navFile)+'\nexports.audit={navigationConfig,settingsConfig,getAllNavItems};',{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const context={exports:{}};vm.runInNewContext(navCode,context);const nav=context.exports.audit;
for(const f of clients){const a=ast.get(f),definitions=[];for(const st of a.statements){if(ts.isFunctionDeclaration(st)&&st.name)definitions.push([st.name.text,st]);if(ts.isVariableStatement(st))for(const d of st.declarationList.declarations){if(!d.initializer)continue;if(ts.isArrowFunction(d.initializer)||ts.isFunctionExpression(d.initializer))definitions.push([d.name.getText(a),d.initializer]);if(ts.isObjectLiteralExpression(d.initializer))for(const p of d.initializer.properties)if(ts.isPropertyAssignment(p)&&(ts.isArrowFunction(p.initializer)||ts.isFunctionExpression(p.initializer)))definitions.push([d.name.getText(a)+'.'+p.name.getText(a),p.initializer]);}}
 for(const [name,node] of definitions){const endpoints=[],calls=[];visit(node,n=>{if(ts.isCallExpression(n)&&ts.isIdentifier(n.expression))calls.push(n.expression.text);if(ts.isStringLiteral(n)||ts.isNoSubstitutionTemplateLiteral(n)||ts.isTemplateExpression(n)){let v=ts.isStringLiteral(n)?n.text:n.getText(a).slice(1,-1);v=v.replace(/\$\{([A-Z_]+)\}/g,(all,k)=>Object.hasOwn(bases,k)?bases[k]:all).replace(/\$\{[^}]+\}/g,'{dynamic}');if(v.startsWith('/')&&!v.includes(' '))endpoints.push(v.split('?')[0]);}});methods[f+'#'+name]={client:f,name,endpoints:[...new Set(endpoints)],calls,line:a.getLineAndCharacterOfPosition(node.getStart()).line+1};}
}
for(let pass=0;pass<5;pass++)for(const m of Object.values(methods))m.endpoints=[...new Set([...m.endpoints,...(m.calls||[]).filter(n=>!['apiCall','apiCallResult','authFetch','seoFetch','seoToolsFetch','seoToolsJson'].includes(n)).flatMap(n=>methods[m.client+'#'+n]?.endpoints||[])])];
for(const [f,a] of ast){const bindings={};for(const st of a.statements){if(!ts.isImportDeclaration(st)||!ts.isStringLiteral(st.moduleSpecifier))continue;const target=resolve(f,st.moduleSpecifier.text),b=st.importClause?.namedBindings;if(!clients.includes(target)||!b)continue;if(ts.isNamespaceImport(b))bindings[b.name.text]={client:target,prefix:''};else for(const e of b.elements)bindings[e.name.text]={client:target,prefix:(e.propertyName?.text||e.name.text)+'.'};}
 visit(a,n=>{if(!ts.isCallExpression(n)||!ts.isPropertyAccessExpression(n.expression))return;const pieces=n.expression.getText(a).replace(/\s/g,'').split('.'),binding=bindings[pieces[0]];if(!binding)return;const name=binding.prefix+pieces.slice(1).join('.');if(methods[binding.client+'#'+name]&&!records[f].apiCalls.some(c=>c.client===binding.client&&c.name===name))records[f].apiCalls.push({client:binding.client,name,line:a.getLineAndCharacterOfPosition(n.getStart()).line+1});});}
const excluded=new Set([...clients,'src/components/Layout.tsx','src/components/MaybeLayout.tsx','src/components/PageShell.tsx','src/components/AuthShell.tsx','src/components/SettingsGear.tsx','src/components/SearchModal.tsx','src/components/FloatingAgent.tsx','src/components/SupportWidget.tsx']);
function closure(f){const seen=new Set();function go(x){if(seen.has(x)||excluded.has(x))return;seen.add(x);for(const d of records[x]?.imports||[])go(d);}go(f);return [...seen];}
const inventory=JSON.parse(fs.readFileSync('docs/execution/workspace-aws-inventory-20261007.json','utf8')).return_value;
const live=inventory.apis.flatMap(a=>a.routes.map(r=>{const integration=a.integrations.find(i=>r.Target==='integrations/'+i.id);return {...r,lambda:integration?.uri?.split(':function:')[1]?.split(':')[0]||null,api:a.id};}));
function routeMatch(ep){return live.filter(r=>{const gateway=r.RouteKey.split(' ').slice(1).join(' ');const a=ep.replace(/\/$/,'').split('/'),b=gateway.replace(/\/$/,'').split('/');for(let i=0;i<b.length;i++){if(b[i].includes('{proxy+}'))return a.length>i;if(a[i]===undefined)return false;if(!a[i].includes('{')&&!b[i].includes('{')&&a[i]!==b[i])return false;}return a.length===b.length;});}
const pages=files.filter(f=>f.startsWith('src/pages/')&&!/\/_/.test(f)).map(f=>{let route='/'+f.slice('src/pages/'.length).replace(/\.(tsx?|jsx?)$/,'').replace(/(^|\/)index$/,'');route=route.replace(/\/$/,'')||'/';const deps=closure(f),calls=deps.flatMap(d=>records[d].apiCalls.map(c=>({...c,file:d})));const keys=[...new Set(calls.map(c=>c.client+'#'+c.name))];const apiMethods=keys.map(k=>methods[k]||{name:k,endpoints:[]});const endpoints=[...new Set(apiMethods.flatMap(m=>m.endpoints))];const direct=deps.flatMap(d=>records[d].directRequests.map(c=>({...c,file:d}))).filter(c=>!clients.includes(c.file));const r=records[f];const text=source.get(f);return {route,file:f,scope:route.startsWith('/workspace')?'workspace':'public',lines:r.lines,imports:r.imports,dependencies:deps,nav:nav.getAllNavItems().filter(n=>n.path.split('?')[0].replace(/\/$/,'')===route),apiMethods,endpoints,routeMatches:endpoints.map(e=>({endpoint:e,matches:routeMatch(e).map(x=>({route:x.RouteKey,lambda:x.lambda}))})),directRequests:direct,flags:[...new Set(deps.flatMap(d=>records[d].flags))],pageImports:deps.filter(d=>d!==f&&d.startsWith('src/pages/')),redirects:[...text.matchAll(/(?:router\.(?:replace|push)|window\.location\.(?:replace|assign))\(\s*['"]([^'"]+)/g)].map(m=>m[1]),shell:/\b(?:MaybeLayout|Layout|PageShell)\b/.test(text),placeholder:/<(?:ComingSoon|EmptyState)\b/.test(text)};});
const apiCoverage=Object.values(methods).map(m=>({...m,pages:pages.filter(p=>p.apiMethods.some(x=>x.client===m.client&&x.name===m.name)).map(p=>p.route)}));
const routeCoverage=live.map(r=>({...r,pages:pages.filter(p=>p.routeMatches.some(m=>m.matches.some(x=>x.route===r.RouteKey))).map(p=>p.route)}));
const out={generatedAt:new Date().toISOString(),head:require('child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),limitations:['Import reachability is static and may include inactive tabs; it does not prove runtime health.','Endpoint matches currently compare paths across methods; method parity requires manual inspection.','Dynamic URL variables and indirect object-method API exports may need manual tracing.','No credential values or customer records read.'],counts:{pages:pages.length,workspace:pages.filter(p=>p.scope==='workspace').length,public:pages.filter(p=>p.scope==='public').length,navEntries:nav.getAllNavItems().length,sidebarTopLevel:nav.navigationConfig.length,settingsGroups:nav.settingsConfig.length,functions:inventory.functions.length,routes:live.length,tables:inventory.tables.length},navigation:{sidebar:nav.navigationConfig,settings:nav.settingsConfig},pages,apiCoverage,routeCoverage,records};
fs.writeFileSync('docs/execution/workspace-page-inventory-20261007.json',JSON.stringify(out,null,2)+'\n');
const q=x=>'"'+String(x??'').replace(/"/g,'""')+'"';fs.writeFileSync('docs/execution/workspace-pages-20261007.csv',[['Route','Scope','File','Lines','Navigation labels','API helpers','Endpoint paths','Imported page routes','Flags','Redirect targets'].map(q).join(','),...pages.map(p=>[p.route,p.scope,p.file,p.lines,p.nav.map(x=>x.label).join('; '),p.apiMethods.map(x=>x.name).join('; '),p.endpoints.join('; '),p.pageImports.join('; '),p.flags.join('; '),p.redirects.join('; ')].map(q).join(','))].join('\n')+'\n');
console.log(JSON.stringify({counts:out.counts,unlisted:pages.filter(p=>p.scope==='workspace'&&!p.nav.length).map(p=>p.route),seo:pages.filter(p=>p.route.startsWith('/workspace/seo')).map(p=>({route:p.route,helpers:p.apiMethods.map(x=>x.client+':'+x.name),direct:p.directRequests}))},null,2));
